/**
 * Three groups of topic words for game generation.
 * Any word from any group should combine with any word from the other groups
 * to form a viable 2D multiplayer game concept.
 */

/** Where the game takes place / what the world looks like */
export const SETTINGS = [
  "underwater",
  "space",
  "jungle",
  "medieval",
  "candy",
  "pirate",
  "haunted",
  "desert",
  "arctic",
  "volcanic",
  "farm",
  "library",
  "kitchen",
  "toy box",
  "cave",
  "cloud",
  "neon city",
  "wild west",
  "fairy tale",
  "prehistoric",
  "cyberpunk",
  "steampunk",
  "garden",
  "graveyard",
  "circus",
  "supermarket",
  "train",
  "rooftop",
  "sewer",
  "beach",
  "factory",
  "museum",
  "school",
  "airport",
  "castle",
  "dungeon",
  "forest",
  "swamp",
  "mountain",
  "island",
  "moon",
  "asteroid",
  "submarine",
  "treehouse",
  "ant hill",
  "beehive",
  "aquarium",
  "zoo",
  "playground",
  "construction site",
  "junkyard",
  "warehouse",
  "laboratory",
  "bakery",
  "arcade",
  "stadium",
  "pool",
  "garage",
  "attic",
  "basement",
  "office",
  "mall",
  "highway",
  "bridge",
  "canyon",
  "glacier",
  "coral reef",
  "deep sea",
  "rainforest",
  "tundra",
  "savanna",
  "oasis",
  "mine",
  "vineyard",
  "orchard",
  "greenhouse",
  "pet shop",
  "laundromat",
  "bowling alley",
  "skate park",
  "campsite",
  "lighthouse",
  "windmill",
  "clock tower",
  "hot air balloon",
  "shipwreck",
  "abandoned mine",
  "mushroom forest",
  "crystal cave",
  "floating islands",
  "volcano crater",
  "sunken temple",
  "frozen lake",
  "bamboo forest",
  "sand dunes",
  "coral kingdom",
  "storm cloud",
  "magma chamber",
  "enchanted well",
  "haunted mansion",
  "robot factory",
  "cheese moon",
  "pillow fort",
  "blanket cave",
  "bathtub ocean",
  "sock drawer",
  "cereal bowl",
  "pizza planet",
  "donut island",
  "spaghetti junction",
  "waffle house",
  "pancake stack",
  "snow globe",
  "music box",
  "board game",
  "pinball machine",
  "vending machine",
  "washing machine",
  "disco floor",
  "bounce house",
  "trampoline park",
  "hamster wheel",
  "ant farm",
  "fish tank",
  "bird cage",
  "terrarium",
  "dollhouse",
  "lego city",
  "paper world",
  "chalk drawing",
  "watercolor painting",
  "pixel world",
  "neon sign",
  "stained glass",
  "comic book",
  "pop-up book",
  "origami land",
  "clay world",
  "felt craft",
  "tin foil kingdom",
  "cardboard city",
  "bubble world",
  "rainbow bridge",
  "northern lights",
  "thunderstorm",
  "tornado alley",
  "meteor shower",
  "eclipse",
  "sunrise",
  "twilight zone",
  "dream world",
  "nightmare realm",
  "mirror dimension",
  "upside-down world",
  "tiny world",
  "giant world",
  "backwards world",
  "black and white world",
  "silent movie",
  "retro TV",
  "video tape",
  "radio tower",
  "telephone wire",
  "conveyor belt",
  "assembly line",
  "rube goldberg",
  "domino chain",
  "marble run",
];

/** What players do / core game activity */
export const ACTIVITIES = [
  "basketball",
  "soccer",
  "hockey",
  "dodgeball",
  "tag",
  "racing",
  "fishing",
  "cooking",
  "painting",
  "gardening",
  "wrestling",
  "jousting",
  "bowling",
  "golf",
  "tennis",
  "archery",
  "fencing",
  "boxing",
  "sumo",
  "curling",
  "surfing",
  "skiing",
  "skateboarding",
  "rock climbing",
  "swimming",
  "diving",
  "flying",
  "treasure hunting",
  "mining",
  "building",
  "demolishing",
  "stacking",
  "balancing",
  "juggling",
  "herding",
  "catching",
  "throwing",
  "pushing",
  "pulling",
  "bouncing",
  "rolling",
  "sliding",
  "spinning",
  "launching",
  "catapulting",
  "pinball",
  "bumper cars",
  "go-karts",
  "relay race",
  "obstacle course",
  "tug of war",
  "capture the flag",
  "king of the hill",
  "hot potato",
  "musical chairs",
  "hide and seek",
  "keep away",
  "monkey in the middle",
  "freeze tag",
  "red light green light",
  "simon says",
  "egg and spoon race",
  "sack race",
  "three-legged race",
  "wheelbarrow race",
  "polo",
  "volleyball",
  "badminton",
  "table tennis",
  "foosball",
  "air hockey",
  "darts",
  "frisbee",
  "boomerang throwing",
  "snowball fight",
  "water balloon fight",
  "pillow fight",
  "food fight",
  "pie throwing",
  "bubble blowing",
  "kite flying",
  "balloon popping",
  "whack-a-mole",
  "crane game",
  "ring toss",
  "bean bag toss",
  "horseshoes",
  "shuffleboard",
  "croquet",
  "bocce ball",
  "lawn bowling",
  "disc golf",
  "mini golf",
  "billiards",
  "marble shooting",
  "paper airplane racing",
  "boat racing",
  "chariot racing",
  "drag racing",
  "demolition derby",
  "jousting tournament",
  "sword fighting",
  "snowboard cross",
  "roller derby",
  "bumper boats",
  "log rolling",
  "cheese rolling",
  "greased pig catching",
  "chicken herding",
  "sheep shearing",
  "cow milking",
  "apple picking",
  "berry picking",
  "mushroom hunting",
  "gem collecting",
  "coin collecting",
  "stamp collecting",
  "bug catching",
  "butterfly netting",
  "ghost hunting",
  "monster wrangling",
  "dragon taming",
  "robot battling",
  "mech fighting",
  "tank battling",
  "spaceship dogfight",
  "jousting on ostriches",
  "chariot pulled by cats",
  "racing on turtles",
  "riding hamsters",
  "pogo stick racing",
  "unicycle racing",
  "shopping cart racing",
  "bed racing",
  "bathtub racing",
  "office chair racing",
  "lawnmower racing",
  "vacuum cleaner racing",
  "pizza delivery",
  "mail sorting",
  "package stacking",
  "dish washing",
  "laundry folding",
  "sandwich making",
  "sushi rolling",
  "cake decorating",
  "ice cream scooping",
  "popcorn popping",
  "pancake flipping",
  "burger flipping",
  "waffle ironing",
  "toast launching",
  "egg cracking",
  "soup stirring",
  "salad tossing",
  "smoothie blending",
  "candy crushing",
  "bubble wrapping",
  "gift wrapping",
  "snowman building",
  "sandcastle building",
  "tower building",
  "bridge building",
  "fort building",
  "wall climbing",
  "rope swinging",
  "vine swinging",
  "trapeze swinging",
  "tightrope walking",
  "pole vaulting",
  "high jumping",
  "long jumping",
  "triple jumping",
  "hurdle jumping",
  "limbo",
];

/** What makes it weird / the twist */
export const TWISTS = [
  "with magnets",
  "in the dark",
  "on ice",
  "with portals",
  "while shrinking",
  "with gravity flips",
  "on conveyor belts",
  "with bouncy walls",
  "while growing",
  "with teleporters",
  "in slow motion",
  "with clones",
  "while spinning",
  "on trampolines",
  "with wind",
  "with explosions",
  "with shields",
  "while invisible",
  "with grappling hooks",
  "on a timer",
  "with power-ups",
  "while tiny",
  "while giant",
  "with mirrors",
  "backwards",
  "upside down",
  "with fog",
  "with lightning",
  "while slippery",
  "with sticky surfaces",
  "with force fields",
  "with lasers",
  "with bubbles",
  "with chains",
  "with springs",
  "with rockets",
  "with parachutes",
  "with jetpacks",
  "in zero gravity",
  "with boomerangs",
  "with time rewind",
  "with screen wrap",
  "with shrinking arena",
  "with rising water",
  "with falling platforms",
  "with moving walls",
  "with rotating floor",
  "with rubber bands",
  "with suction cups",
  "with soap",
  "with glue",
  "with oil slicks",
  "with banana peels",
  "with speed boosts",
  "with freeze rays",
  "with shrink rays",
  "with growth rays",
  "with swapped controls",
  "with mirrored controls",
  "with delayed controls",
  "with shared controls",
  "on a seesaw",
  "on a turntable",
  "on a pendulum",
  "on a catapult",
  "on a zipline",
  "on stilts",
  "on roller skates",
  "on pogo sticks",
  "on unicycles",
  "on hoverboards",
  "in bumper bubbles",
  "in hamster balls",
  "in cardboard boxes",
  "in shopping carts",
  "in inner tubes",
  "wearing jet boots",
  "wearing sumo suits",
  "wearing moon shoes",
  "carrying eggs",
  "balancing plates",
  "juggling torches",
  "holding hands",
  "tied together",
  "back to back",
  "blindfolded",
  "one-handed",
  "hopping on one foot",
  "crawling",
  "crab walking",
  "moonwalking",
  "with double jump",
  "with wall jump",
  "with dash",
  "with teleport dodge",
  "with ground pound",
  "with charge attack",
  "with spin attack",
  "with boomerang attack",
  "with ricochet shots",
  "with homing missiles",
  "with land mines",
  "with bear traps",
  "with trip wires",
  "with smoke bombs",
  "with flash bangs",
  "with decoys",
  "with disguises",
  "with camouflage",
  "with x-ray vision",
  "with echo location",
  "with heat vision",
  "with night vision",
  "where everything bounces",
  "where everything explodes",
  "where everything is edible",
  "where everything is alive",
  "where colors change",
  "where size changes randomly",
  "where speed changes randomly",
  "where gravity shifts randomly",
  "where the floor is lava",
  "where the walls close in",
  "where everything melts",
  "where everything freezes",
  "where everything floats",
  "where everything sinks",
  "where day and night cycle fast",
  "where seasons change fast",
  "where weather changes constantly",
  "where music controls physics",
  "where sound makes waves",
  "where yelling makes power",
  "where silence is golden",
  "where color is power",
  "where shadows are solid",
  "where reflections are real",
  "where drawings come alive",
  "where photos are portals",
  "where words are weapons",
  "where numbers are ammo",
  "where math solves problems",
  "where rhythm is everything",
  "but everyone is round",
  "but everyone is square",
  "but everyone is a triangle",
  "but everyone is a blob",
  "but everyone looks the same",
  "but roles swap every 30 seconds",
  "but the leader gets a handicap",
  "but last place gets a boost",
  "but scoring is reversed",
  "but the map is random each round",
  "but the rules change each round",
  "but one player is the referee",
  "but one player is a ghost",
  "but one player is giant",
  "but teams shuffle mid-game",
];
